require 'rod'

require 'rlp/wiki/version'
require 'rlp/wiki/database'
require 'rlp/wiki/model'
require 'rlp/wiki/page'
require 'rlp/wiki/concept'
require 'rlp/wiki/category'
require 'rlp/wiki/anchor'
require 'rlp/wiki/translation'
require 'rlp/wiki/redirect'
require 'rlp/wiki/term'
require 'rlp/wiki/kind'
require 'rlp/wiki/infobox'
require 'rlp/wiki/occurrence'
require 'rlp/wiki/semantic_predicates'
