source "http://rubygems.org"

# Specify your gem's dependencies in rlp-wiki.gemspec
gemspec

gem 'slop', "~> 3.4.7"
gem 'ZenTest'
gem 'cycr', '~> 0.2.0'
gem 'htmlentities'
gem 'srx-english', '~> 0.1.2'
gem 'progress', :git => 'git://github.com/djstrong/progress.git'
gem 'colors'
gem 'thin'
gem 'rake'
gem 'sparql-client'

gem 'rod', :git => 'git://github.com/apohllo/rod.git', :tag => 'v0.7.2.6rc1'
gem 'rod-rest'
gem 'hadoop-csv', :git => 'git://github.com/apohllo/hadoop-csv.git'
gem 'syntax', :path => 'file://../../category-parsing/'
