require 'mapping/service/cyc_name_service'
require 'mapping/service/pos_service'
require 'mapping/service/type_service'
require 'mapping/service/term_merger'
require 'mapping/service/category_mapping_service'
require 'mapping/service/genus_proximum_mapping_service'
require 'mapping/service/article_mapping_service'
require 'mapping/service/pattern_mapping_service'
